- [Crystal Material, PPKTP]
- [Crystal Poling Period, 25.0]
- [Crystal Refractive Index X, kato]
- [Crystal Refractive Index Y, koenig]
- [Crystal Refractive Index Z, fradkin]
- [Pump wavelength from, 1540.0]
- [Pump wavelength single, 1550.0]
- [Pump wavelength to, 1560.0]
- [Pump pulsewidth from, 1.0]
- [Pump pulsewidth single, 2.0]
- [Pump pulsewidth to, 5.0]
- [Pump pulse shape, Sech^2]
- [Pump pulsewidth apply deconvolution factor, true]
- [Temperature from, 18.0]
- [Temperature single, 24.0]
- [Temperature to, 50.0]
