- [Crystal Material, PPKTP]
- [Crystal Poling Period From, 3.9999999999999996e-05]
- [Crystal Poling Period Single, 4.625e-05]
- [Crystal Poling Period To, 4.9999999999999996e-05]
- [Crystal Refractive Index X, kato]
- [Crystal Refractive Index Y, koenig]
- [Crystal Refractive Index Z, fradkin]
- [QPM Order, -1]
- [Pump wavelength from, 7.680000000000001e-07]
- [Pump wavelength single, 7.750000000000001e-07]
- [Pump wavelength to, 7.8e-07]
- [SI wavelength from, 1.54e-06]
- [SI wavelength single, 1.5500000000000002e-06]
- [SI wavelength to, 1.56e-06]
- [Pump pulsewidth from, 1.0e-12]
- [Pump pulsewidth single, 2.98e-12]
- [Pump pulsewidth to, 5.0e-12]
- [Pump pulse shape, Sech^2]
- [Pump pulsewidth apply deconvolution factor, false]
- [Crystal Temperature from, 0.0]
- [Crystal Temperature single, 15.75]
- [Crystal Temperature to, 100.0]
- [Crystal Length from, 0.002]
- [Crystal Length single, 0.03]
- [Crystal Length to, 0.05]
- [JSI wavelength range, 8.0e-09]
- [JSI resolution, 50]
- [Purity wavelength resolution, 50]
- [Purity wavelength range, 8.0e-09]
- [Purity tau resolution, 10]
- [SI filter Idler Type, None]
- [SI filter Signal Type, None]
- [SI filter Idler center wavelength, 1.5500000000000002e-06]
- [SI filter Signal center wavelength, 1.5500000000000002e-06]
- [SI filter Idler FWHM, 3.0000000000000004e-09]
- [SI filter Signal FWHM, 1.0e-09]
