- [Crystal Material, PPKTP]
- [Crystal Poling Period, 46.2]
- [Crystal Refractive Index X, kato]
- [Crystal Refractive Index Y, koenig]
- [Crystal Refractive Index Z, fradkin]
- [Pump wavelength from, 770.0]
- [Pump wavelength single, 775.0]
- [Pump wavelength to, 780.0]
- [SI wavelength from, 1540.0]
- [SI wavelength single, 1550.0]
- [SI wavelength to, 1560.0]
- [Pump pulsewidth from, 1.0]
- [Pump pulsewidth single, 2.0]
- [Pump pulsewidth to, 5.0]
- [Pump pulse shape, Sech^2]
- [Pump pulsewidth apply deconvolution factor, true]
- [Temperature from, 0.0]
- [Temperature single, 24.0]
- [Temperature to, 100.0]
