- [Crystal Material, PPKTP]
- [Crystal Poling Period From, 4.6e-05]
- [Crystal Poling Period Single, 9.999999999999999e-06]
- [Crystal Poling Period To, 4.7e-05]
- [Crystal Refractive Index X, kato]
- [Crystal Refractive Index Y, koenig]
- [Crystal Refractive Index Z, fradkin]
- [QPM Order, 1]
- [Pump wavelength from, 4.049e-07]
- [Pump wavelength single, 4.0500000000000004e-07]
- [Pump wavelength to, 4.0510000000000005e-07]
- [SI wavelength from, 1.5300000000000002e-06]
- [SI wavelength single, 1.5500000000000002e-06]
- [SI wavelength to, 1.57e-06]
- [Pump pulsewidth from, 1e-13]
- [Pump pulsewidth single, 1e-09]
- [Pump pulsewidth to, 6e-13]
- [Pump pulse shape, Sech^2]
- [Pump pulsewidth apply deconvolution factor, false]
- [Crystal Temperature from, 34.0]
- [Crystal Temperature single, 35.7]
- [Crystal Temperature to, 36.0]
- [Crystal Length from, 0.002]
- [Crystal Length single, 0.03]
- [Crystal Length to, 0.05]
- [JSI wavelength range, 5e-09]
- [JSI resolution, 1000]
- [Purity wavelength resolution, 50]
- [Purity wavelength range, 1.2000000000000002e-08]
- [Purity tau resolution, 50]
- [SI filter Idler Type, None]
- [SI filter Signal Type, None]
- [SI filter Idler center wavelength, 1.545e-06]
- [SI filter Signal center wavelength, 1.545e-06]
- [SI filter Idler FWHM, 1e-09]
- [SI filter Signal FWHM, 1e-09]
- [HOM interference plot resolution, 21]
- [HOM interference plot phase, 0]
- [HOM interference plot range, 5e-11]
- [FWHM plot resolution, 25]
- [FWHM decimal precision, 1]
