- [Crystal Material, PPKTP]
- [Crystal Poling Period From, 4.6e-05]
- [Crystal Poling Period Single, 9.999999999999999e-06]
- [Crystal Poling Period To, 4.7e-05]
- [Crystal Refractive Index X, kato]
- [Crystal Refractive Index Y, koenig]
- [Crystal Refractive Index Z, fradkin]
- [QPM Order, 1]
- [Pump wavelength from, 4.04e-07]
- [Pump wavelength single, 4.0500000000000004e-07]
- [Pump wavelength to, 4.06e-07]
- [SI wavelength from, 8.000000000000001e-07]
- [SI wavelength single, 8.100000000000001e-07]
- [SI wavelength to, 8.200000000000001e-07]
- [Pump pulsewidth from, 1e-13]
- [Pump pulsewidth single, 6.25e-09]
- [Pump pulsewidth to, 2e-11]
- [Pump pulse shape, Gaussian]
- [Pump pulsewidth apply deconvolution factor, false]
- [Crystal Temperature from, 10.0]
- [Crystal Temperature single, 38.5]
- [Crystal Temperature to, 50.0]
- [Crystal Length from, 0.002]
- [Crystal Length single, 0.01]
- [Crystal Length to, 0.05]
- [JSI wavelength range, 1e-09]
- [JSI resolution, 1000]
- [Purity wavelength resolution, 49]
- [Purity wavelength range, 2.5000000000000002e-08]
- [Purity tau resolution, 50]
- [SI filter Idler Type, None]
- [SI filter Signal Type, None]
- [SI filter Idler center wavelength, 8.100000000000001e-07]
- [SI filter Signal center wavelength, 8.100000000000001e-07]
- [SI filter Idler FWHM, 1e-09]
- [SI filter Signal FWHM, 1e-09]
- [HOM interference plot resolution, 501]
- [HOM interference plot phase, 0]
- [HOM interference plot range, 5e-11]
- [FWHM plot resolution, 25]
- [FWHM decimal precision, 1]
