- [Crystal Material, PPKTP]
- [Crystal Poling Period, 4.62e-05]
- [Crystal Refractive Index X, kato]
- [Crystal Refractive Index Y, koenig]
- [Crystal Refractive Index Z, fradkin]
- [QPM Order, -1]
- [Pump wavelength from, 7.680000000000001e-07]
- [Pump wavelength single, 7.750000000000001e-07]
- [Pump wavelength to, 7.8e-07]
- [SI wavelength from, 1.54e-06]
- [SI wavelength single, 1.5500000000000002e-06]
- [SI wavelength to, 1.56e-06]
- [Pump pulsewidth from, 1.0e-12]
- [Pump pulsewidth single, 2.0e-12]
- [Pump pulsewidth to, 5.0e-12]
- [Pump pulse shape, Sech^2]
- [Pump pulsewidth apply deconvolution factor, true]
- [Temperature from, 15.0]
- [Temperature single, 24.0]
- [Temperature to, 50.0]
