- [Crystal Material, PPKTP]
- [Crystal Poling Period From, 3.9999999999999996e-05]
- [Crystal Poling Period Single, 4.62495e-05]
- [Crystal Poling Period To, 4.9999999999999996e-05]
- [Crystal Refractive Index X, kato]
- [Crystal Refractive Index Y, koenig]
- [Crystal Refractive Index Z, fradkin]
- [QPM Order, -1]
- [Pump wavelength from, 5.313e-07]
- [Pump wavelength single, 7.731000000000001e-07]
- [Pump wavelength to, 5.332999999999999e-07]
- [SI wavelength from, 1.25e-06]
- [SI wavelength single, 1.5462000000000001e-06]
- [SI wavelength to, 1.35e-06]
- [Pump pulsewidth from, 0.0]
- [Pump pulsewidth single, 2e-12]
- [Pump pulsewidth to, 2e-14]
- [Pump pulse shape, Gaussian]
- [Pump pulsewidth apply deconvolution factor, false]
- [Crystal Temperature from, 0.0]
- [Crystal Temperature single, 22.8]
- [Crystal Temperature to, 100.0]
- [Crystal Length from, 0.01]
- [Crystal Length single, 0.03]
- [Crystal Length to, 0.05]
- [JSI wavelength range, 3.0000000000000004e-08]
- [JSI resolution, 500]
- [Purity wavelength resolution, 50]
- [Purity wavelength range, 1.2000000000000002e-08]
- [Purity tau resolution, 50]
- [SI filter Idler Type, None]
- [SI filter Signal Type, None]
- [SI filter Idler center wavelength, 1.5458e-06]
- [SI filter Signal center wavelength, 1.5458e-06]
- [SI filter Idler FWHM, 3.0000000000000004e-09]
- [SI filter Signal FWHM, 3.0000000000000004e-09]
- [HOM interference plot resolution, 11]
- [HOM interference plot range, 2e-11]
- [FWHM plot resolution, 25]
- [FWHM decimal precision, 3]
